# Generated by Django 3.0.10 on 2020-10-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Users', 'Clients')
    ]
