# Generated by Django 3.0.10 on 2020-10-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_20201029_2321'),
    ]

    operations = [
        migrations.RenameModel('Clients', 'Client')
    ]
