# Generated by Django 3.0.10 on 2020-10-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20201029_2327'),
    ]

    operations = [
        migrations.RenameModel('Binfo', 'Sinfo')
    ]
