# Generated by Django 3.0.10 on 2020-10-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20201031_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Sinfo',
        ),
        migrations.AlterField(
            model_name='client',
            name='itemsbid',
            field=models.ManyToManyField(blank=True, to='bidding.Binfo'),
        ),
    ]
