# Generated by Django 3.0.10 on 2020-10-31 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20201031_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Binfo',
            new_name='Sinfo',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='itemsbid',
            new_name='items_onsale',
        ),
        migrations.DeleteModel(
            name='Iinfo',
        ),
    ]
