# Generated by Django 3.0.10 on 2020-11-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_auto_20201031_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinfo',
            name='idesc',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
