# Generated by Django 3.0.10 on 2020-11-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_sinfo_idesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='items_onsale',
        ),
        migrations.AddField(
            model_name='client',
            name='items_onsale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Sinfo'),
        ),
    ]
